# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cox_llk_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMSurv_cox_llk_cpp`, y, XData, beta, lambda, weight)
}

cox_grad_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMSurv_cox_grad_cpp`, y, XData, beta, lambda, weight)
}

cox_dgrad_cpp <- function(y, XData, beta, lambda, weight) {
    .Call(`_ELMSurv_cox_dgrad_cpp`, y, XData, beta, lambda, weight)
}

bjimpute <- function(y, cen, x, inibeta) {
    .Call(`_ELMSurv_bjimpute`, y, cen, x, inibeta)
}

mm_mult <- function(x, y) {
    .Call(`_ELMSurv_mm_mult`, x, y)
}

testDFtoNM <- function(x) {
    .Call(`_ELMSurv_testDFtoNM`, x)
}

scaleNM <- function(x1) {
    .Call(`_ELMSurv_scaleNM`, x1)
}

kernmat <- function(xtrain, kernel_type, kernel_para, xtest) {
    .Call(`_ELMSurv_kernmat`, xtrain, kernel_type, kernel_para, xtest)
}

mrl <- function(y, cen) {
    .Call(`_ELMSurv_mrl`, y, cen)
}

